In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
Moviestreaming = pd.read_excel(r"C:\Users\NNAEMEKA DIVINE\Downloads\messy_movie_streaming_dataset.xlsx")
Moviestreaming

,User_ID,User_Name,Email_Phone,Country,Subscription_Type,Genre_Watched,Watch_Time_Hours,Rating
0,U1105,sarah connor,"bob@yahoo.com,09011223344",canada,Standard,Action,56.32,2.0
1,U1108,jane smith,"john@example.com,08012345678",uk,Basic,Action,81.96,2.0
2,U1141,bob lee,"bob@yahoo.com,09011223344",Canada,Basic,SCI-FI,72.94,NaN
3,U1055,Alice Brown,"bob@yahoo.com,09011223344",canada,Standard,SCI-FI,NaN,3.0
4,U1094,sarah connor,"bob@yahoo.com,09011223344",USA,Premium,Drama,37.47,4.0
...,...,...,...,...,...,...,...,...
155,U1071,John Doe,"john@example.com,08012345678",Nigeria,premium,SCI-FI,66.03,5.0
156,U1106,Chris Evans,"alice@gmail.com,07098765432",UK,basic,comedy,82.92,NaN
157,U1014,sarah connor,"bob@yahoo.com,09011223344",UK,basic,action,58.87,2.0
158,U1092,bob lee,"john@example.com,08012345678",UK,premium,comedy,29.33,2.0
159,U1102,sarah connor,"alice@gmail.com,07098765432",Nigeria,Basic,Drama,15.91,3.0

In [3]:
Moviestreaming.head()

,User_ID,User_Name,Email_Phone,Country,Subscription_Type,Genre_Watched,Watch_Time_Hours,Rating
0,U1105,sarah connor,"bob@yahoo.com,09011223344",canada,Standard,Action,56.32,2.0
1,U1108,jane smith,"john@example.com,08012345678",uk,Basic,Action,81.96,2.0
2,U1141,bob lee,"bob@yahoo.com,09011223344",Canada,Basic,SCI-FI,72.94,NaN
3,U1055,Alice Brown,"bob@yahoo.com,09011223344",canada,Standard,SCI-FI,NaN,3.0
4,U1094,sarah connor,"bob@yahoo.com,09011223344",USA,Premium,Drama,37.47,4.0

In [4]:
Moviestreaming.tail()

,User_ID,User_Name,Email_Phone,Country,Subscription_Type,Genre_Watched,Watch_Time_Hours,Rating
155,U1071,John Doe,"john@example.com,08012345678",Nigeria,premium,SCI-FI,66.03,5.0
156,U1106,Chris Evans,"alice@gmail.com,07098765432",UK,basic,comedy,82.92,NaN
157,U1014,sarah connor,"bob@yahoo.com,09011223344",UK,basic,action,58.87,2.0
158,U1092,bob lee,"john@example.com,08012345678",UK,premium,comedy,29.33,2.0
159,U1102,sarah connor,"alice@gmail.com,07098765432",Nigeria,Basic,Drama,15.91,3.0

In [5]:
Moviestreaming.isnull().sum()

User_ID               8
User_Name            10
Email_Phone          10
Country              11
Subscription_Type     9
Genre_Watched         9
Watch_Time_Hours      9
Rating               29
dtype: int64

### Removing duplicates

In [6]:
Moviestreaming.duplicated().sum()

np.int64(12)

In [7]:
Moviestreaming.drop_duplicates(inplace = True)
Moviestreaming

,User_ID,User_Name,Email_Phone,Country,Subscription_Type,Genre_Watched,Watch_Time_Hours,Rating
0,U1105,sarah connor,"bob@yahoo.com,09011223344",canada,Standard,Action,56.32,2.0
1,U1108,jane smith,"john@example.com,08012345678",uk,Basic,Action,81.96,2.0
2,U1141,bob lee,"bob@yahoo.com,09011223344",Canada,Basic,SCI-FI,72.94,NaN
3,U1055,Alice Brown,"bob@yahoo.com,09011223344",canada,Standard,SCI-FI,NaN,3.0
4,U1094,sarah connor,"bob@yahoo.com,09011223344",USA,Premium,Drama,37.47,4.0
...,...,...,...,...,...,...,...,...
155,U1071,John Doe,"john@example.com,08012345678",Nigeria,premium,SCI-FI,66.03,5.0
156,U1106,Chris Evans,"alice@gmail.com,07098765432",UK,basic,comedy,82.92,NaN
157,U1014,sarah connor,"bob@yahoo.com,09011223344",UK,basic,action,58.87,2.0
158,U1092,bob lee,"john@example.com,08012345678",UK,premium,comedy,29.33,2.0
159,U1102,sarah connor,"alice@gmail.com,07098765432",Nigeria,Basic,Drama,15.91,3.0


### Cleaning of User name column

In [8]:
Moviestreaming["User_Name"].value_counts()

User_Name
bob lee         30
sarah connor    28
jane smith      23
John Doe        22
Chris Evans     21
Alice Brown     18
Name: count, dtype: int64

In [9]:
## solving the inconstitent text format issue
Moviestreaming["User_Name"] = Moviestreaming["User_Name"].str.strip().str.lower().str.title()
Moviestreaming["User_Name"]

0      Sarah Connor
1        Jane Smith
2           Bob Lee
3       Alice Brown
4      Sarah Connor
           ...
155        John Doe
156     Chris Evans
157    Sarah Connor
158         Bob Lee
159    Sarah Connor
Name: User_Name, Length: 148, dtype: object

In [10]:
Moviestreaming["User_Name"].value_counts()

User_Name
Bob Lee         30
Sarah Connor    28
Jane Smith      23
John Doe        22
Chris Evans     21
Alice Brown     18
Name: count, dtype: int64

### Cleaning of Email_phone column

In [11]:
Moviestreaming["Email_Phone"].value_counts()

Email_Phone
bob@yahoo.com,09011223344       57
alice@gmail.com,07098765432     44
john@example.com,08012345678    41
Name: count, dtype: int64

In [12]:
## splitting the email_phone column
Moviestreaming[["Email_Address", "Phone_Number"]] = Moviestreaming["Email_Phone"].str.split(",", expand= True)
Moviestreaming[["Email_Address", "Phone_Number"]]

        Email_Address Phone_Number
0       bob@yahoo.com  09011223344
1    john@example.com  08012345678
2       bob@yahoo.com  09011223344
3       bob@yahoo.com  09011223344
4       bob@yahoo.com  09011223344
..                ...          ...
155  john@example.com  08012345678
156   alice@gmail.com  07098765432
157     bob@yahoo.com  09011223344
158  john@example.com  08012345678
159   alice@gmail.com  07098765432

[148 rows x 2 columns]

### Cleaning country column

In [13]:
Moviestreaming["Country"].value_counts()

Country
UK         22
USA        21
uk         20
Usa        20
Canada     18
Nigeria    14
nigeria    14
canada     12
Name: count, dtype: int64

In [14]:
Moviestreaming["Country"] = Moviestreaming["Country"].str.strip().str.lower().str.title()
Moviestreaming["Country"]

0       Canada
1           Uk
2       Canada
3       Canada
4          Usa
        ...
155    Nigeria
156         Uk
157         Uk
158         Uk
159    Nigeria
Name: Country, Length: 148, dtype: object

In [15]:
Moviestreaming["Country"] = Moviestreaming["Country"].str.replace("Usa", "USA",case = True, regex= True)
Moviestreaming

,User_ID,User_Name,Email_Phone,Country,Subscription_Type,Genre_Watched,Watch_Time_Hours,Rating,Email_Address,Phone_Number
0,U1105,Sarah Connor,"bob@yahoo.com,09011223344",Canada,Standard,Action,56.32,2.0,bob@yahoo.com,09011223344
1,U1108,Jane Smith,"john@example.com,08012345678",Uk,Basic,Action,81.96,2.0,john@example.com,08012345678
2,U1141,Bob Lee,"bob@yahoo.com,09011223344",Canada,Basic,SCI-FI,72.94,NaN,bob@yahoo.com,09011223344
3,U1055,Alice Brown,"bob@yahoo.com,09011223344",Canada,Standard,SCI-FI,NaN,3.0,bob@yahoo.com,09011223344
4,U1094,Sarah Connor,"bob@yahoo.com,09011223344",USA,Premium,Drama,37.47,4.0,bob@yahoo.com,09011223344
...,...,...,...,...,...,...,...,...,...,...
155,U1071,John Doe,"john@example.com,08012345678",Nigeria,premium,SCI-FI,66.03,5.0,john@example.com,08012345678
156,U1106,Chris Evans,"alice@gmail.com,07098765432",Uk,basic,comedy,82.92,NaN,alice@gmail.com,07098765432
157,U1014,Sarah Connor,"bob@yahoo.com,09011223344",Uk,basic,action,58.87,2.0,bob@yahoo.com,09011223344
158,U1092,Bob Lee,"john@example.com,08012345678",Uk,premium,comedy,29.33,2.0,john@example.com,08012345678
159,U1102,Sarah Connor,"alice@gmail.com,07098765432",Nigeria,Basic,Drama,15.91,3.0,alice@gmail.com,07098765432

### Cleaning Subscription_type column

In [16]:
Moviestreaming["Subscription_Type"].value_counts()

Subscription_Type
Standard    30
Basic       27
standard    25
Premium     23
premium     21
basic       17
Name: count, dtype: int64

In [17]:
Moviestreaming["Subscription_Type"] = Moviestreaming["Subscription_Type"].str.strip().str.lower().str.title()
Moviestreaming["Subscription_Type"]

0      Standard
1         Basic
2         Basic
3      Standard
4       Premium
         ...
155     Premium
156       Basic
157       Basic
158     Premium
159       Basic
Name: Subscription_Type, Length: 148, dtype: object

In [18]:
Moviestreaming.info()

<class 'pandas.core.frame.DataFrame'>
Index: 148 entries, 0 to 159
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   User_ID            144 non-null    object
 1   User_Name          142 non-null    object
 2   Email_Phone        142 non-null    object
 3   Country            141 non-null    object
 4   Subscription_Type  143 non-null    object
 5   Genre_Watched      143 non-null    object
 6   Watch_Time_Hours   143 non-null    float64
 7   Rating             124 non-null    float64
 8   Email_Address      142 non-null    object
 9   Phone_Number       142 non-null    object
dtypes: float64(2), object(8)
memory usage: 12.7+ KB

### Cleaning Genre_watched column

In [19]:
Moviestreaming["Genre_Watched"] = Moviestreaming["Genre_Watched"].str.strip().str.lower().str.title()
Moviestreaming["Genre_Watched"]

0      Action
1      Action
2      Sci-Fi
3      Sci-Fi
4       Drama
        ...
155    Sci-Fi
156    Comedy
157    Action
158    Comedy
159     Drama
Name: Genre_Watched, Length: 148, dtype: object

### Dropping the transaction date column

In [20]:
Moviestreaming = Moviestreaming.drop("Email_Phone", axis=1)

In [21]:
Moviestreaming

,User_ID,User_Name,Country,Subscription_Type,Genre_Watched,Watch_Time_Hours,Rating,Email_Address,Phone_Number
0,U1105,Sarah Connor,Canada,Standard,Action,56.32,2.0,bob@yahoo.com,09011223344
1,U1108,Jane Smith,Uk,Basic,Action,81.96,2.0,john@example.com,08012345678
2,U1141,Bob Lee,Canada,Basic,Sci-Fi,72.94,NaN,bob@yahoo.com,09011223344
3,U1055,Alice Brown,Canada,Standard,Sci-Fi,NaN,3.0,bob@yahoo.com,09011223344
4,U1094,Sarah Connor,USA,Premium,Drama,37.47,4.0,bob@yahoo.com,09011223344
...,...,...,...,...,...,...,...,...,...
155,U1071,John Doe,Nigeria,Premium,Sci-Fi,66.03,5.0,john@example.com,08012345678
156,U1106,Chris Evans,Uk,Basic,Comedy,82.92,NaN,alice@gmail.com,07098765432
157,U1014,Sarah Connor,Uk,Basic,Action,58.87,2.0,bob@yahoo.com,09011223344
158,U1092,Bob Lee,Uk,Premium,Comedy,29.33,2.0,john@example.com,08012345678
159,U1102,Sarah Connor,Nigeria,Basic,Drama,15.91,3.0,alice@gmail.com,07098765432

In [22]:
Moviestreaming.dropna(how = "all",inplace= True)
Moviestreaming

,User_ID,User_Name,Country,Subscription_Type,Genre_Watched,Watch_Time_Hours,Rating,Email_Address,Phone_Number
0,U1105,Sarah Connor,Canada,Standard,Action,56.32,2.0,bob@yahoo.com,09011223344
1,U1108,Jane Smith,Uk,Basic,Action,81.96,2.0,john@example.com,08012345678
2,U1141,Bob Lee,Canada,Basic,Sci-Fi,72.94,NaN,bob@yahoo.com,09011223344
3,U1055,Alice Brown,Canada,Standard,Sci-Fi,NaN,3.0,bob@yahoo.com,09011223344
4,U1094,Sarah Connor,USA,Premium,Drama,37.47,4.0,bob@yahoo.com,09011223344
...,...,...,...,...,...,...,...,...,...
155,U1071,John Doe,Nigeria,Premium,Sci-Fi,66.03,5.0,john@example.com,08012345678
156,U1106,Chris Evans,Uk,Basic,Comedy,82.92,NaN,alice@gmail.com,07098765432
157,U1014,Sarah Connor,Uk,Basic,Action,58.87,2.0,bob@yahoo.com,09011223344
158,U1092,Bob Lee,Uk,Premium,Comedy,29.33,2.0,john@example.com,08012345678
159,U1102,Sarah Connor,Nigeria,Basic,Drama,15.91,3.0,alice@gmail.com,07098765432

In [23]:

Moviestreaming.isnull().sum()

User_ID               3
User_Name             5
Country               6
Subscription_Type     4
Genre_Watched         4
Watch_Time_Hours      4
Rating               23
Email_Address         5
Phone_Number          5
dtype: int64

### Converting null values to error

In [24]:
Moviestreaming = Moviestreaming.fillna("UNKNOWN")
Moviestreaming

,User_ID,User_Name,Country,Subscription_Type,Genre_Watched,Watch_Time_Hours,Rating,Email_Address,Phone_Number
0,U1105,Sarah Connor,Canada,Standard,Action,56.32,2.0,bob@yahoo.com,09011223344
1,U1108,Jane Smith,Uk,Basic,Action,81.96,2.0,john@example.com,08012345678
2,U1141,Bob Lee,Canada,Basic,Sci-Fi,72.94,UNKNOWN,bob@yahoo.com,09011223344
3,U1055,Alice Brown,Canada,Standard,Sci-Fi,UNKNOWN,3.0,bob@yahoo.com,09011223344
4,U1094,Sarah Connor,USA,Premium,Drama,37.47,4.0,bob@yahoo.com,09011223344
...,...,...,...,...,...,...,...,...,...
155,U1071,John Doe,Nigeria,Premium,Sci-Fi,66.03,5.0,john@example.com,08012345678
156,U1106,Chris Evans,Uk,Basic,Comedy,82.92,UNKNOWN,alice@gmail.com,07098765432
157,U1014,Sarah Connor,Uk,Basic,Action,58.87,2.0,bob@yahoo.com,09011223344
158,U1092,Bob Lee,Uk,Premium,Comedy,29.33,2.0,john@example.com,08012345678
159,U1102,Sarah Connor,Nigeria,Basic,Drama,15.91,3.0,alice@gmail.com,07098765432

In [25]:
Moviestreaming[["Watch_Time_Hours","Rating"]] = Moviestreaming[["Watch_Time_Hours","Rating"]].replace(["UNKNOWN", 0],pd.NA)
Moviestreaming

,User_ID,User_Name,Country,Subscription_Type,Genre_Watched,Watch_Time_Hours,Rating,Email_Address,Phone_Number
0,U1105,Sarah Connor,Canada,Standard,Action,56.32,2.0,bob@yahoo.com,09011223344
1,U1108,Jane Smith,Uk,Basic,Action,81.96,2.0,john@example.com,08012345678
2,U1141,Bob Lee,Canada,Basic,Sci-Fi,72.94,<NA>,bob@yahoo.com,09011223344
3,U1055,Alice Brown,Canada,Standard,Sci-Fi,<NA>,3.0,bob@yahoo.com,09011223344
4,U1094,Sarah Connor,USA,Premium,Drama,37.47,4.0,bob@yahoo.com,09011223344
...,...,...,...,...,...,...,...,...,...
155,U1071,John Doe,Nigeria,Premium,Sci-Fi,66.03,5.0,john@example.com,08012345678
156,U1106,Chris Evans,Uk,Basic,Comedy,82.92,<NA>,alice@gmail.com,07098765432
157,U1014,Sarah Connor,Uk,Basic,Action,58.87,2.0,bob@yahoo.com,09011223344
158,U1092,Bob Lee,Uk,Premium,Comedy,29.33,2.0,john@example.com,08012345678
159,U1102,Sarah Connor,Nigeria,Basic,Drama,15.91,3.0,alice@gmail.com,07098765432

### Answering insight driven questions

In [26]:
# What is the relationship between watch_time_hours and rating
Insight1 = Moviestreaming["Watch_Time_Hours"].corr(Moviestreaming["Rating"])
Insight1

np.float64(0.030566143847019774)

In [27]:
# what is average watch time per subscription_Type
Insight2 = Moviestreaming.groupby("Subscription_Type")["Watch_Time_Hours"].mean().reset_index(name = "Average_watchtimehour").sort_values(by="Average_watchtimehour",ascending=False)
Insight2

  Subscription_Type Average_watchtimehour
1           Premium             57.644091
2          Standard             55.933962
0             Basic             55.869048
3           UNKNOWN               35.5975

In [28]:
# Which country has the highest users 
Insight3 = Moviestreaming.groupby("Country")["User_Name"].count().reset_index(name = "Number of users").sort_values(by="Number of users",ascending=False)
Insight3

   Country  Number of users
4       Uk               42
3      USA               41
0   Canada               30
1  Nigeria               28
2  UNKNOWN                6

In [29]:
#What is the most watched genre
Insight4= Moviestreaming['Genre_Watched'].value_counts().to_frame(name='Count').reset_index()
Insight4

  Genre_Watched  Count
0        Action     44
1        Sci-Fi     35
2         Drama     35
3        Comedy     29
4       UNKNOWN      4

In [30]:
# What is the most watched genre and average rating
Insight5 = Moviestreaming.groupby('Genre_Watched')['Rating'].mean().reset_index(name='Average rating').sort_values(by= 'Average rating', ascending=False)
Insight5

  Genre_Watched Average rating
4       UNKNOWN           3.25
3        Sci-Fi       3.193548
1        Comedy            3.0
0        Action            2.9
2         Drama       2.714286

In [31]:
# which subcription type has the  lowest rating
Insight6 = Moviestreaming.groupby("Subscription_Type")["Rating"].mean().reset_index(name = "Average_rating").sort_values(by = "Average_rating",ascending= False) 
Insight6

  Subscription_Type Average_rating
3           UNKNOWN            5.0
2          Standard       3.066667
0             Basic       2.833333
1           Premium            2.8

In [32]:
# What is the number of users per subscription type
Insight7 = Moviestreaming.groupby("Subscription_Type")["User_Name"].count().reset_index(name = "Number of users").sort_values(by = "Number of users",ascending= False) 
Insight7

  Subscription_Type  Number of users
2          Standard               55
0             Basic               44
1           Premium               44
3           UNKNOWN                4

### Duplicating the clean dataset

In [33]:
# to export a cleaned dataset to csv
Moviestreaming.to_csv("Cleaned_Movie_Streaming.csv",index = False)

In [34]:
Moviestreaming.copy()

,User_ID,User_Name,Country,Subscription_Type,Genre_Watched,Watch_Time_Hours,Rating,Email_Address,Phone_Number
0,U1105,Sarah Connor,Canada,Standard,Action,56.32,2.0,bob@yahoo.com,09011223344
1,U1108,Jane Smith,Uk,Basic,Action,81.96,2.0,john@example.com,08012345678
2,U1141,Bob Lee,Canada,Basic,Sci-Fi,72.94,<NA>,bob@yahoo.com,09011223344
3,U1055,Alice Brown,Canada,Standard,Sci-Fi,<NA>,3.0,bob@yahoo.com,09011223344
4,U1094,Sarah Connor,USA,Premium,Drama,37.47,4.0,bob@yahoo.com,09011223344
...,...,...,...,...,...,...,...,...,...
155,U1071,John Doe,Nigeria,Premium,Sci-Fi,66.03,5.0,john@example.com,08012345678
156,U1106,Chris Evans,Uk,Basic,Comedy,82.92,<NA>,alice@gmail.com,07098765432
157,U1014,Sarah Connor,Uk,Basic,Action,58.87,2.0,bob@yahoo.com,09011223344
158,U1092,Bob Lee,Uk,Premium,Comedy,29.33,2.0,john@example.com,08012345678
159,U1102,Sarah Connor,Nigeria,Basic,Drama,15.91,3.0,alice@gmail.com,07098765432